# Constants


BLOCK_SIZE = 20
SCOREBOARD_SIZE=4*BLOCK_SIZE
WINDOW_SIZE = (30*BLOCK_SIZE, 30*BLOCK_SIZE)

NUM_BLOCKS_WIDE = WINDOW_SIZE[0] // BLOCK_SIZE
NUM_BLOCKS_HIGH = (WINDOW_SIZE[1]-SCOREBOARD_SIZE) // BLOCK_SIZE
WALL_COUNT = 10
DOT_COUNT = 20
WALL_LENGTH=[4,10]

FONT_NAME = 'freesansbold.ttf'
FONT_SIZE = BLOCK_SIZE
